#using an official image of node.js runtime
FROM node:22-alpine

#set the working dir inside container
WORKDIR /app

#copy all package.json file in working dir
COPY package*.json ./

#instll dependencies
RUN npm install

COPY . .

ENV port=3000

CMD ["node", "index.js"]